新增測試覆蓋率檢查，確保測試覆蓋率超過設定閾值

diff --git a/.github/workflows/testing.golang.v1.yaml b/.github/workflows/testing.golang.v1.yaml
--- a/.github/workflows/testing.golang.v1.yaml
+++ b/.github/workflows/testing.golang.v1.yaml
@@ -71,4 +71,20 @@ jobs:
         run: |
           cd ${{inputs.GO_BUILD_PATH}} && go build . && cd -
           go mod vendor
-          go test -v ./...
+          go test -cover -coverpkg "./transport/...,./internal/service,./internal/repo" "./test" -coverprofile=coverage.out
+          go tool cover -func coverage.out
+      - name: Quality Gate - Test coverage shall be above threshold
+        env:
+          TEST_COVERAGE_THRESHOLD: 60
+        run: |
+          echo "Quality Gate: checking test coverage is above threshold ..."
+          echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
+          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+          echo "Current test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "OK"
+          else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Failed"
+              exit 1
+          fi
